

###
curl http://192.168.1.24:8001/consumers/

###

curl http://192.168.1.24:8001/services/

###

curl http://192.168.1.24:8001/routes/

###

curl http://192.168.1.24:8000/quake?apikey=pochi&limit=1

###

curl http://192.168.1.24:8000/quake?apikey=bar&limit=1
